CREATE TABLE Research(
 IdResearch INT AUTO_INCREMENT PRIMARY KEY,
 Research VARCHAR(100) NOT NULL,
 Category VARCHAR(50) NOT NULL,
 Organisation VARCHAR(50) NOT NULL,
 Researcher VARCHAR(50) NOT NULL,
 Overview VARCHAR(1000) NOT NULL
);
SELECT * FROM Research;

DROP TABLE Research;

INSERT INTO Research(Research,Category, Organisation,Researcher,Overview) VALUES("Advanced Biological Research System","Biological Research","NASA","Jeffrey Williams","Advanced Biological Research System (ABRS) [NASA] is a singlelocker system providing two growth chambers. Each growth chamber is a closed system capable of independently controlling temperature, illumination and atmospheric composition to grow a variety of biological organisms including plants, microorganisms and small arthropods (insects and spiders).");
INSERT INTO Research(Research,Category, Organisation,Researcher,Overview) VALUES("BioLab Experiment Facility","Biological Research","ESA","Frank De Winne ","BioLab Experiment Laboratory (BioLab) [ESA] can be used to perform space biology experiments on microorganisms, cells, tissue cultures, small plants and small invertebrates. Such studies provide a better understanding of the effects of microgravity and space radiation on biological organisms. BioLab includes an incubator, a glovebox, two freezer units and two centrifuges to simulate the effects of gravity");
INSERT INTO Research(Research,Category, Organisation,Researcher,Overview) VALUES("Kriogem-3M","Biological Research","Roscosmos"," Oleg Kononenko","Kriogem-3M [Roscosmos] is a refrigerator-incubator used for the stowage of biological samples or medical kits and for the culture and incubation of bioreactors such as Recomb-K, Lutch-2.");
INSERT INTO Research(Research,Category, Organisation,Researcher,Overview) VALUES("TBU-N Low temperature incubator","Biological Research","Roscosmos","Sergey Ryzhikov","TBU-N Low temperature incubator [Roscosmos] provides a refrigerated environment for carrying out a variety of experiments in human life sciences, biology and biotechnology.");
INSERT INTO Research(Research,Category, Organisation,Researcher,Overview) VALUES("TBU-V High-temperature incubator","Biological Research","Roscosmos","Anatoly Ivanishin","TBU-V High-temperature incubator [Roscosmos] enables a variety of experiments in human life sciences, biology and biotechnology at elevated temperatures.");
INSERT INTO Research(Research,Category, Organisation,Researcher,Overview) VALUES("Commercial Generic Bioprocessing Apparatus","Biological Research","NASA,Commercial","Mike Hopkins","The Commercial Generic Bioprocessing Apparatus (CGBA) [NASA, Commercial] provides programmable, accurate temperature control— from cold stowage to a customizable incubator designed for biotechnology experiments in microgravity. CGBA can be used in a wide variety of biological studies, such as protein crystal growth, small insect habitats and plant development, as well as antibiotic producing bacteria and cell culture studies.");
INSERT INTO Research(Research,Category, Organisation,Researcher,Overview) VALUES("Space Automated Bioproduct Laboratory","Biological Research","Nasa,Commercial"," Reid Wiseman","The Space Automated Bioproduct Laboratory (SABL) [NASA, Commercial] provides the researcher with advanced incubator technology and complements the existing CGBA incubator. SABL supports a wide variety of experiments to support the development of applications for use on Earth by pharmaceutical, biotechnology and agribusiness companies. SABL provides a  temperature range of -5°C to +43°C, and is designed to be user friendly for the crewmember");
INSERT INTO Research(Research,Category, Organisation,Researcher,Overview) VALUES("KUBIK","Biological Research","ESA"," Fyodor Yurchikhin","KUBIK [ESA] is a cubic box container measuring 37 cm3 and composed of a thermal chamber with a volume of 9.36 L, which can function both as an incubator or a cooler. It operates from 6°C to 38°C with a stability of 0.1°C. The thermal chamber can be equipped with removable inserts designed for maximal sample flexibility. The KUBIK has a centrifuge insert, which has a selectable acceleration from 0.2g to 2g in 0.1g increments.");
INSERT INTO Research(Research,Category, Organisation,Researcher,Overview) VALUES("Vegetable Production System","Biological Research","NASA","Kimiya Yui","The Vegetable Production System (Veggie) [NASA] is an advanced plant growth chamber that supports a variety of experiment objectives. The growth chamber is the largest on the ISS at this time and allows for larger-sized plants to be grown than in previous ISS experiments. Additionally, the large adjustable LED light bank makes Veggie an ideal facility for experiments requiring a controlled light source. The total plant growing area is 0.13 m2 , and water is provided passively to the rooting media using capillary connections to a reservoir.");
INSERT INTO Research(Research,Category, Organisation,Researcher,Overview) VALUES("European Modular Cultivation System ","Biological Research","ESA, NASA","Thomas Reiter","European Modular Cultivation System (EMCS) [ESA, NASA] is an ESA experiment facility that is dedicated to studying plant biology in a reduced-gravity environment. It supports the cultivation, stimulation and crew-assisted operation of biological experiments under controlled conditions (e.g., temperature, atmospheric composition, water supply and illumination). The facility has performed multi-generation (seed-to-seed) experiments and studies the effects of gravity and light on early development and growth, signal perception and transduction in plant tropisms. Experiments with cell and tissue cultures are also being planned for the EMCS.");
INSERT INTO Research(Research,Category, Organisation,Researcher,Overview) VALUES("Plant Habitat","Biological Research","NASA","Rick Mastracchio","The Plant Habitat [NASA] is a fully automated facility that will be used to conduct plant bioscience research on the ISS. Plant Habitat provides a large, enclosed, environmentally controlled chamber designed to support commercial and fundamental plant research or other bioscience research onboard the International Space Station (ISS) for at least one year of continuous operation without maintenance and integrates proven microgravity plant growth technologies with newly developed fault tolerance and recovery technology to increase overall efficiency, reliability, and robustness");
INSERT INTO Research(Research,Category, Organisation,Researcher,Overview) VALUES("Aquatic Habitat","Biological Research","JAXA, Roscosmos","Kevin Ford","Aquatic Habitat (AQH) [JAXA, Roscosmos], located in the MSPR facility, is designed for breeding small fresh-water Medaka or Zebrafish for up to 90 days in the microgravity environment in the ISS. Such fish provide many advantages as model animals for microgravity research of biological processes and systems. The AQH is composed of two aquariums that contain automatic feeding systems, day/night cycle LED lighting, charge-coupled device (CCD) cameras and a water quality control system comprised of a biological filter with nitrifying bacteria and a physical filter with activated charcoal for particulate and organic waste removal.");
INSERT INTO Research(Research,Category, Organisation,Researcher,Overview) VALUES("Microscope Observation System","Biological Research","JAXA","Karen Nyberg","The JAXA Microscope Observation System (Fluorescence Microscope) [JAXA] is located in the MSPR or in the cabin area. It is an inverted fluorescence microscope, a Leica DMI 6000B. It has 6 different objective lenses, with a monochrome CCD camera. The microscope is equipped with an LED illumination unit and can perform time-lapse videomicroscopy. It also is equipped with a stage heater (up to 40°C) to enable cell culture observation. The Fluorescence Microscope is controlled and remotely commanded from the ground once samples are placed into it by the onboard crew. It has been used for biology (cultured cell and fish larva) and plant experiments onboard the ISS/Kibo");
INSERT INTO Research(Research,Category, Organisation,Researcher,Overview) VALUES("Muscle Atrophy Research Exercise System","Human Physiology and Adaptation Research","ESA"," Chris Hadfield and Tom Marshburn","Muscle Atrophy Research Exercise System (MARES) [ESA] is used for research on musculoskeletal, biomechanical and neuromuscular human physiology to better understand the effects of microgravity on these related systems. This instrument is capable of assessing the strength of isolated muscle groups around joints by controlling and measuring relationships between position/velocity and torque/ force as a function of time");
INSERT INTO Research(Research,Category, Organisation,Researcher,Overview) VALUES("Advanced Resistive Exercise Device ","Human Physiology and Adaptation Research","NASA","Dan Burbank","Advanced Resistive Exercise Device (ARED) [NASA] provides resistive exercise capabilities to crewmembers on the ISS. The ARED also collects data regarding the parameters (loads, repetitions, stroke, etc.) associated with crew exercise, and transmits it to the ground.");
INSERT INTO Research(Research,Category, Organisation,Researcher,Overview) VALUES("Combined Operational Load Bearing External Resistive Exercise Treadmill","Human Physiology and Adaptation Research","NASA","Mikhail Kornienko","Combined Operational Load Bearing External Resistive Exercise Treadmill (COLBERT) [NASA] is an exercise treadmill that can be used to collect data such as body loading, duration of session, and speed for each crewmember.");
INSERT INTO Research(Research,Category, Organisation,Researcher,Overview) VALUES("Percutaneous Electrical Muscle Stimulator","Human Physiology and Adaptation Research","ESA","Andreas Mogensen","Percutaneous Electrical Muscle Stimulator (PEMS) [ESA] is a portable, self-contained neuromuscular research device that may be used standalone or in conjunction with other physiological instruments. The purpose of this device is to deliver electrical pulse stimulation to non-thoracic muscle groups of a human test subject, thereby creating contractile responses from the muscles. It is capable of providing single, variable amplitude pulses or pulse trains according to a pre-adjusted program.");
INSERT INTO Research(Research,Category, Organisation,Researcher,Overview) VALUES("Cycle Ergometer with Vibration Isolation System","Human Physiology and Adaptation Research","NASA","r Barry Wilmore","The Cycle Ergometer with Vibration Isolation System (CEVIS) [NASA] is a structurally isolated aerobic exercise cycle that serves as a countermeasure to cardiovascular deconditioning on orbit.");
INSERT INTO Research(Research,Category, Organisation,Researcher,Overview) VALUES("Combustion Integrated Rack","Physical Science Research","NASA","Frank De Winne","Combustion Integrated Rack (CIR) [NASA] is used to perform sustained, systematic combustion experiments in microgravity. It consists of an optics bench, a combustion chamber, a fuel and oxidizer management system, environmental management systems, interfaces for science diagnostics and experiment specific equipment, as well as 5 different cameras to observe the patterns of combustion in microgravity for a wide variety of gasses and materials. The CIR provides up to 90% of the required hardware to perform a majority of future microgravity combustion experiments onboard the ISS and the remaining 10% of the hardware (fuel, igniters, etc.) is provided by the specific investigation teams");
INSERT INTO Research(Research,Category, Organisation,Researcher,Overview) VALUES("Advanced Combustion via Microgravity Experiments","Physical Science Research","NASA","Furukawa poses","The Advanced Combustion via Microgravity Experiments (ACME) [NASA] enables a suite of investigations and is focused on advanced combustion technology via fundamental microgravity research to improve efficiency and reduce pollutant emission in practical terrestrial combustion. The ACME investigations will operate in the CIR.");
INSERT INTO Research(Research,Category, Organisation,Researcher,Overview) VALUES("Materials Science Research Rack (MSRR-1)","Physical Science Research","ESA, NASA","Frank De Winne","Materials Science Research Rack (MSRR-1) [ESA, NASA] is a powerful multi-user facility that enables researchers by providing hardware to control the thermal, environmental and vacuum conditions of experiments, as well as monitor experiments using video, and supply power and data handling for experiment instrumentation.");
INSERT INTO Research(Research,Category, Organisation,Researcher,Overview) VALUES("Kobairo Rack (Kobairo)","Physical Science Research","JAXA","Cady Coleman","The Kobairo Rack (Kobairo) [JAXA] contains the Gradient Heating Furnace (GHF) [JAXA], which provides all utility interfaces for this material science furnace. The GHF is a vacuum furnace that contains 3 heating blocks, and is used mainly to conduct high-quality crystal growth experiments using unidirectional solidification. The 3 heater units can generate the high temperature gradients needed to produce large-scale pure crystals.");
INSERT INTO Research(Research,Category, Organisation,Researcher,Overview) VALUES("Additive Manufacturing Facility ","Physical Science Research","NASA,Commercial","Tim Kopra","The Additive Manufacturing Facility (AMF) [NASA, Commercial] enables the production of components on the ISS for both NASA and commercial objectives. Parts, entire experiments, and tools can be created on demand utilizing the AMF that is installed into an EXPRESS Rack locker location. The AMF is capable of producing parts out of a wide variety of thermopolymers, including engineered plastics.");
INSERT INTO Research(Research,Category, Organisation,Researcher,Overview) VALUES("Fluids Integrated Rack","Physical Science Research","NASA","Jeff Williams","Fluids Integrated Rack (FIR) [NASA] is a multi-user fluid physics research facility designed to accommodate and image a wide variety of microgravity fluid experiments. FIR features a large user-configurable volume for experiments. The FIR provides data acquisition and control, sensor interfaces, laser and white light sources, advanced imaging capabilities, power, cooling and other resources. The FIR will host fluid physics investigations into areas such as complex fluids (colloids, gels), instabilities (bubbles), interfacial phenomena (wetting and capillary action) and phase changes (boiling and cooling).");
INSERT INTO Research(Research,Category, Organisation,Researcher,Overview) VALUES("Ryutai Rack (Ryutai)","Physical Science Research","JAXA","Koichi Wakata","Ryutai Rack (Ryutai) [JAXA] is a multipurpose, multi-user rack system that supports various fluid physics experiments. Ryutai consists of 4 sub-racks. Fluid Physics Experiment Facility (FPEF) [JAXA] is a multi-user experiment facility to investigate fluid physics phenomena in a microgravity environment. Solution Crystallization Observation Facility (SCOF) [JAXA] investigates morphology and growth of crystals.");
INSERT INTO Research(Research,Category, Organisation,Researcher,Overview) VALUES("Cosmic Ray Detectors and Ionosphere Probes","Earth and Space Science Research","Roscosmos","t Elena Serova","Cosmic Ray Detectors and Ionosphere Probes [Roscosmos] are important for ongoing studies of cosmic rays and the low-Earth orbit environment. Several external investigations and instrument packages are available including BTN-Neutron (neutron flux detector) and Vsplesk (gamma ray and high-energy charged particle detector). Obstanovka is another suite of detectors used to measure several ionosphere parameters and plasma-wave characteristics.");
INSERT INTO Research(Research,Category, Organisation,Researcher,Overview) VALUES("Photospectrometric System (FSS) ","Earth and Space Science Research","JAXA","Fyodor Yurchikhin","Photospectrometric System (FSS) is used for monitoring natural disasters (Uragan) and ecological monitoring (Econ). FSS uses a spectral range of 350-1050 nm and resolution of better than 3 nm. In all, this suit of instruments practically and efficiently increases the ability to perform scientific and Earth observation experiments from the ISS");
INSERT INTO Research(Research,Category, Organisation,Researcher,Overview) VALUES("Window Observational Research Facility (WORF)","Earth and Space Science Research","NASA"," Ron Garan","The Window Observational Research Facility (WORF) [NASA] provides a unique ISS facility for conducting crew-tended or automatic Earth observation and scientific research using the Destiny module’s large optical-quality window. WORF is a multipurpose facility that provides structural support hardware, avionics, thermal conditioning and optical quality protection in support of a wide variety of remote sensing instruments and scientific investigation.");
INSERT INTO Research(Research,Category, Organisation,Researcher,Overview) VALUES("Crew Earth Observations","Earth and Space Science Research","NASA","Luca Parmitano","The Crew Earth Observations (CEO) Facility [NASA] utilizes the ISS crew and handheld, visible-wavelength digital cameras (currently Nikon D4 series) to photograph the Earth surface and atmosphere from low-Earth orbit. A variety of available camera lenses allows for both wide-field, low spatial resolution panoramic and Earth-limb imagery (useful for atmospheric science studies), and very high spatial resolution (~ 3 meters/pixel), targeted ground imagery that supports urban, environmental, coastal, agricultural and geologic research and applications.");
INSERT INTO Research(Research,Category, Organisation,Researcher,Overview) VALUES("Sun Monitoring on the External Payload Facility of Columbus","Earth and Space Science Research","ESA","Hurricane Matthew","Sun Monitoring on the External Payload Facility of Columbus (Solar) [ESA] was a monitoring observatory that measured the solar spectral irradiance");
INSERT INTO Research(Research,Category, Organisation,Researcher,Overview) VALUES("Global Transmission Services (GTS)","Technology Demonstration Research","ESA","Jeff Williams","Global Transmission Services (GTS) [ESA, Roscosmos] is a continuously operating facility, located within the Russian Segment of the ISS, which tests the receiving conditions of time and data signals from dedicated receivers on the ground. Special coding of the time signal allows the receiver to determine the local time anywhere on the Earth. The main objective of this hardware is to verify the performance and accuracy of a time signal transmitted to the Earth’s surface");
INSERT INTO Research(Research,Category, Organisation,Researcher,Overview) VALUES("Bar","Technology Demonstration Research","Roscosmos","Roman Romanenko","Bar [Roscosmos] uses a unique set of instruments for conducting ultrasonic probing, measuring and mapping spacecraft temperatures and pyroendoscopic analysis of potentially dangerous locations and conditions onboard the ISS as a result of material degradation or corrosion during operations in orbit. Zones of possible formation of condensation have been revealed, and potential corrosion damage has been evaluated.");
INSERT INTO Research(Research,Category, Organisation,Researcher,Overview) VALUES("Space Communications and Navigation Testbed","Technology Demonstration Research","NASA","Koichi Wakata","The Space Communications and Navigation Testbed (SCAN Testbed) [NASA] consists of a set of reconfigurable software defined radios (SDRs), which have software that can be modified on orbit to allow users to test multiple radio frequency bands using the same hardware. By providing reconfigurable software to an existing radio platform, SCAN Testbed allows different radio vendors the ability to demonstrate unique radio configurations based on the common Space Telecommunications Radio System architecture standard. T");
INSERT INTO Research(Research,Category, Organisation,Researcher,Overview) VALUES("Proboy (Puncture)","Technology Demonstration Research","Roscosmos","Elena Serova","Proboy (Puncture) [Roscos - mos] tests a method associ - ated with fast detection of point of puncture coordi - nates in the ISS module hull (made by a high-speed micrometeoroid or techno - genic particles) with detec - tion of acoustic waves in the module’s cabin air");
INSERT INTO Research(Research,Category, Organisation,Researcher,Overview) VALUES("Vibrolab","Technology Demonstration Research","Roscosmos","Roman Romanenko","Vibrolab [Roscosmos] tests and fine-tunes methods and instruments for monitoring of microaccelerations aboard the ISS Russian Segment associated with implementation of research programs in a microgravity environment");


